### ISSUE TITLE
interactions-tasks issue with http3 module

### ISSUE THREAD

**Issue by stephen-carew** [Catalyst4222/interactions-tasks#2]
My code:
```
@create_task((IntervalTrigger(30)))
async def getData():
  print("we're here")
  edenCollection = eden.getData()

@bot.event
async def on_ready():
  print("I'm ready")


getData.start()
bot.start()

```

The Error:
```
Task exception was never retrieved
future: <Task finished name='Task-16' coro=<Task.fire() done, defined at /Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/site-packages/interactions/ext/tasks/tasks.py:147> exception=RuntimeError('Cannot run the event loop while another loop is running')>
Traceback (most recent call last):
  File "/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/site-packages/http3/api.py", line 37, in request
    return client.request(
  File "/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/site-packages/http3/client.py", line 634, in request
    async_response = concurrency_backend.run(coroutine, *args, **kwargs)
  File "/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/site-packages/http3/concurrency.py", line 240, in run
    return self.loop.run_until_complete(coroutine(*args, **kwargs))
  File "/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py", line 623, in run_until_complete
    self._check_running()
  File "/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py", line 585, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/site-packages/interactions/ext/tasks/tasks.py", line 155, in fire
    res = await self.func(*self.pre_args, *self.args, **self.pre_kwargs, **self.kwargs)
  File "/Users/stephencarew/Bots/ChannelMyFloor/main.py", line 553, in getData
    edenCollection = eden.getData()
  File "/Users/stephencarew/Bots/ChannelMyFloor/eden.py", line 27, in getData
    response = http3.get('website', params=params, cookies=cookies, headers=headers)
  File "/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/site-packages/http3/api.py", line 68, in get
    return request(
  File "/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/site-packages/http3/api.py", line 37, in request
    return client.request(
  File "/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/site-packages/http3/client.py", line 895, in __exit__
    self.close()
  File "/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/site-packages/http3/client.py", line 884, in close
    self.concurrency_backend.run(coroutine)
  File "/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/site-packages/http3/concurrency.py", line 240, in run
    return self.loop.run_until_complete(coroutine(*args, **kwargs))
  File "/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py", line 623, in run_until_complete
    self._check_running()
  File "/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py", line 585, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py:1890: RuntimeWarning: coroutine 'ConnectionPool.close' was never awaited
  handle = self._ready.popleft()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/Users/stephencarew/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py:1890: RuntimeWarning: coroutine 'BaseClient.send' was never awaited
  handle = self._ready.popleft()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by Catalyst4222** [comment]
It seems like the issue is with the `http3` module trying to start the loop after it's already running. The pypi page for it claims that there's async support, so I'd recommend trying to implement it if you haven't already. If that doesn't work, there's the nest_asyncio patch that would likely make it work
